# Generated by Django 5.0.4 on 2024-05-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogrmaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_lectivo', models.DateField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True)),
                ('fecha_fin', models.DateField(blank=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('areaa', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('id_tipo_pago', models.ForeignKey(blank=True, db_column='id_tipo_pago', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pagos.tipopago')),
            ],
            options={
                'db_table': 'cronograma_pago',
            },
        ),
    ]
