# Generated by Django 5.0.4 on 2024-05-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_cronogrmapago'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cronogrmapago',
            table='cronograma_pagos',
        ),
    ]
