# Generated by Django 5.0.6 on 2024-05-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_alter_cronogrmapago_anio_lectivo_pendiente_pagos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='fecha_emision',
            new_name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='mes_cancelado',
        ),
        migrations.AlterField(
            model_name='pagos',
            name='anticipado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='codigo_recibo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='condicion_venta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estado',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='moneda',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='um',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
