# Generated by Django 5.0.6 on 2024-05-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_rename_fecha_emision_pagos_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('deuda', models.BooleanField()),
                ('alumno', models.CharField(max_length=152)),
                ('tipo_de_pago', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'historial_pagos',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='cronogrmapago',
            name='mes_cancelado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='tipo_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
