# Generated by Django 5.0.6 on 2024-07-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_rename_fecha_emision_pagos_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogrmapago',
            name='mes_cancelado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='tipo_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
