# Generated by Django 4.2.4 on 2024-07-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_cronogrmapago_mes_cancelado_pagos_tipo_comprobante'),
        ('pagos', '0006_historialpagos_cronogrmapago_mes_cancelado_and_more'),
    ]

    operations = [
    ]
