# Generated by Django 4.2.4 on 2024-07-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_merge_20240719_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='id_Document',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='codigo_recibo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
