# Generated by Django 5.0.6 on 2024-05-19 17:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosActivos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('usuario', models.CharField(max_length=112)),
                ('id_tipo_usuario', models.BigIntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.CharField(max_length=13)),
                ('fecha_cierre', models.DateField()),
                ('hora_cierre', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'usuarios_activos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'modulos',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('id_modulos', models.ForeignKey(blank=True, db_column='id_modulos', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='application.modulos')),
                ('id_tipo_usuario', models.ForeignKey(blank=True, db_column='id_tipo_usuario', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='application.tipousuario')),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ruta_fotografia', models.CharField(default='https://objetivoligar.com/wp-content/uploads/2017/03/blank-profile-picture-973460_1280-580x580.jpg', max_length=255)),
                ('nombres', models.CharField(blank=True, max_length=50)),
                ('apellido_paterno', models.CharField(blank=True, max_length=30)),
                ('apellido_materno', models.CharField(blank=True, max_length=30)),
                ('dni', models.CharField(blank=True, max_length=8, unique=True)),
                ('celular', models.CharField(blank=True, max_length=9)),
                ('domicilio', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('last_logout', models.DateTimeField(default=None, null=True)),
                ('id_tipo_usuario', models.ForeignKey(blank=True, db_column='id_tipo_usuario', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='application.tipousuario')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
