# Generated by Django 5.0.4 on 2024-04-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='last_login',
        ),
    ]
