# Generated by Django 5.0.4 on 2024-04-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_authuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='last_name',
        ),
    ]
