# Generated by Django 5.0.4 on 2024-04-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_authuser_email_remove_authuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='is_staff',
        ),
    ]
