# Generated by Django 5.0.6 on 2024-05-28 15:51

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='ruta_fotografia',
            field=models.ImageField(default='images/default_img.jpg', upload_to=application.models.upload_image),
        ),
    ]
