# Generated by Django 5.0.4 on 2024-04-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_authuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='is_staff',
        ),
    ]
