# Generated by Django 5.0.7 on 2024-08-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_authuser_ruta_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='ruta_fotografia',
            field=models.CharField(default='https://ontrust-cm.culturadelalegalidad.net/sites/default/files/participantes/profile_pics/anonimo.jpg', max_length=255),
        ),
    ]
