# Generated by Django 5.0.7 on 2024-08-24 01:47

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_authuser_ruta_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='ruta_fotografia',
            field=models.ImageField(default='images/default_img.jpg', upload_to=application.models.upload_image),
        ),
    ]
