# Generated by Django 5.0.7 on 2024-08-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_authuser_ruta_fotografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='ruta_fotografia',
        ),
    ]
