# Generated by Django 5.0.4 on 2024-04-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_authuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='es_personal',
            field=models.BooleanField(default=False),
        ),
    ]
