# Generated by Django 5.0.4 on 2024-04-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_authuser_es_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='es_personal',
        ),
        migrations.AddField(
            model_name='authuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
