# Generated by Django 5.0.4 on 2024-04-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_authuser_es_personal_authuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='authuser',
            name='ruta_fotografica',
            field=models.CharField(default='https://objetivoligar.com/wp-content/uploads/2017/03/blank-profile-picture-973460_1280-580x580.jpg', max_length=255),
        ),
    ]
