# Generated by Django 5.0.4 on 2024-04-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_authuser_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='ruta_fotografica',
            new_name='ruta_fotografia',
        ),
    ]
