# Generated by Django 5.0.7 on 2024-08-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_authuser_ruta_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='ruta_2',
            new_name='ruta_fotografica',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='ruta_fotografia',
        ),
    ]
