# Generated by Django 5.0.4 on 2024-04-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_rename_ruta_fotografica_authuser_ruta_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='apellido_materno',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='apellido_paterno',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='dni',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='nombres',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
