# Generated by Django 5.0.7 on 2024-08-24 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_rename_ruta_2_authuser_ruta_fotografica_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='ruta_fotografica',
            new_name='ruta_fotografia',
        ),
    ]
