# Generated by Django 5.0.4 on 2024-08-27 20:30

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_rename_ruta_fotografica_authuser_ruta_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='ruta_fotografia',
            field=models.ImageField(default='hombre.png', upload_to=application.models.upload_image),
        ),
    ]
