# Generated by Django 5.0.4 on 2024-04-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_authuser_apellido_materno_authuser_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='apellido_materno',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='apellido_paterno',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='dni',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ruta_fotografia',
            field=models.CharField(default='https://objetivoligar.com/wp-content/uploads/2017/03/blank-profile-picture-973460_1280-580x580.jpg', max_length=255, null=True),
        ),
    ]
