# Generated by Django 5.0.4 on 2024-09-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_authuser_ruta_fotografia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['username'], name='application_usernam_482aee_idx'),
        ),
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['is_active'], name='application_is_acti_6db847_idx'),
        ),
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['id_tipo_usuario'], name='application_id_tipo_ea9939_idx'),
        ),
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['email'], name='application_email_343bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['dni'], name='application_dni_ee9198_idx'),
        ),
    ]
