# Generated by Django 5.0.4 on 2024-04-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_authuser_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='ruta_fotografia',
            field=models.CharField(default='https://objetivoligar.com/wp-content/uploads/2017/03/blank-profile-picture-973460_1280-580x580.jpg', max_length=255),
        ),
    ]
