# Generated by Django 5.0.4 on 2024-04-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_authuser_ruta_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='celular',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='domicilio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='sexo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
