# Generated by Django 5.0.4 on 2024-09-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_authuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='authuser',
            name='application_usernam_482aee_idx',
        ),
        migrations.RemoveIndex(
            model_name='authuser',
            name='application_is_acti_6db847_idx',
        ),
        migrations.RemoveIndex(
            model_name='authuser',
            name='application_id_tipo_ea9939_idx',
        ),
        migrations.RemoveIndex(
            model_name='authuser',
            name='application_email_343bf1_idx',
        ),
        migrations.RemoveIndex(
            model_name='authuser',
            name='application_dni_ee9198_idx',
        ),
    ]
