# Generated by Django 5.0.4 on 2024-09-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_authuser_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuariosActivos',
        ),
    ]
