# Generated by Django 5.0.4 on 2024-04-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_authuser_celular_alter_authuser_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='fecha_nacimiento',
            field=models.DateField(default=None),
        ),
    ]
