# Generated by Django 5.0.4 on 2024-04-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_authuser_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
