# Generated by Django 5.0.4 on 2024-04-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alter_authuser_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='ultimo_cierre_fecha',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='authuser',
            name='ultimo_cierre_hora',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='authuser',
            name='ultimo_ingreso_fecha',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='authuser',
            name='ultimo_ingreso_hora',
            field=models.TimeField(default=None),
        ),
    ]
