# Generated by Django 5.0.4 on 2024-04-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_authuser_ultimo_cierre_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
