# Generated by Django 5.0.4 on 2024-04-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_authuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='is_active',
        ),
    ]
