# Generated by Django 5.0.4 on 2024-04-19 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_modulos_permisos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisos',
            name='id_modulo',
        ),
        migrations.AddField(
            model_name='permisos',
            name='id_modulos',
            field=models.ForeignKey(db_column='id_modulos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.modulos'),
        ),
    ]
