# Generated by Django 5.0.4 on 2024-04-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_remove_authuser_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosActivos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('usuario', models.CharField(max_length=112)),
                ('tipo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('ult_ingreso', models.CharField(max_length=27)),
                ('ult_cierre', models.CharField(max_length=27)),
            ],
            options={
                'db_table': 'usuarios_activos',
                'managed': False,
            },
        ),
    ]
