# Generated by Django 5.0.4 on 2024-04-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_alter_authuser_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='apellido_materno',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='apellido_paterno',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='celular',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='dni',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='domicilio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='fecha_nacimiento',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='sexo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
