# Generated by Django 5.0.4 on 2024-04-21 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_alter_authuser_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='id_tipo_usuario',
            field=models.ForeignKey(db_column='id_tipo_usuario', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.tipousuario'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_cierre_fecha',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_cierre_hora',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_ingreso_fecha',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_ingreso_hora',
            field=models.TimeField(default=None, null=True),
        ),
    ]
