# Generated by Django 5.0.4 on 2024-04-21 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_alter_authuser_id_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='id_tipo_usuario',
            field=models.ForeignKey(db_column='id_tipo_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.tipousuario'),
        ),
    ]
