# Generated by Django 5.0.4 on 2024-04-21 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_alter_authuser_id_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='apellido_materno',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='apellido_paterno',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='celular',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='dni',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='domicilio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='fecha_nacimiento',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='id_tipo_usuario',
            field=models.ForeignKey(db_column='id_tipo_usuario', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='application.tipousuario'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_cierre_fecha',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_cierre_hora',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_ingreso_fecha',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_ingreso_hora',
            field=models.TimeField(default=None),
        ),
    ]
