# Generated by Django 5.0.4 on 2024-04-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_alter_authuser_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_cierre_fecha',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_cierre_hora',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_ingreso_fecha',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_ingreso_hora',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
