# Generated by Django 5.0.4 on 2024-04-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_alter_authuser_ultimo_cierre_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='apellido_materno',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='apellido_paterno',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='celular',
            field=models.CharField(default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='dni',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='domicilio',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='nombres',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='sexo',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_cierre_fecha',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_cierre_hora',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_ingreso_fecha',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ultimo_ingreso_hora',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
