# Generated by Django 5.0.4 on 2024-04-21 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_alter_authuser_ultimo_cierre_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='ultimo_cierre_fecha',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='ultimo_cierre_hora',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='ultimo_ingreso_fecha',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='ultimo_ingreso_hora',
        ),
    ]
