# Generated by Django 5.0.4 on 2024-04-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_remove_authuser_ultimo_cierre_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='ultimo_cierre_fecha',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='ultimo_cierre_hora',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='ultimo_ingreso_fecha',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='ultimo_ingreso_hora',
            field=models.TimeField(default=None, null=True),
        ),
    ]
