# Generated by Django 5.0.4 on 2024-04-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_authuser_ultimo_cierre_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='nombres',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
