# Generated by Django 5.0.4 on 2024-04-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_alter_authuser_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='celular',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='dni',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='domicilio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='sexo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
