# Generated by Django 5.0.4 on 2024-04-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_alter_authuser_id_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
