# Generated by Django 5.0.4 on 2024-04-21 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_alter_modulos_descripcion_alter_modulos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='id_modulos',
            field=models.ForeignKey(blank=True, db_column='id_modulos', on_delete=django.db.models.deletion.DO_NOTHING, to='application.modulos'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='id_tipo_usuario',
            field=models.ForeignKey(blank=True, db_column='id_tipo_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='application.tipousuario'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
