# Generated by Django 5.0.4 on 2024-04-21 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_alter_permisos_descripcion_alter_permisos_id_modulos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='id_modulos',
            field=models.ForeignKey(blank=True, db_column='id_modulos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.modulos'),
        ),
    ]
