# Generated by Django 5.0.4 on 2024-04-21 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_alter_permisos_id_modulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='id_tipo_usuario',
            field=models.ForeignKey(blank=True, db_column='id_tipo_usuario', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='application.tipousuario'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='id_tipo_usuario',
            field=models.ForeignKey(blank=True, db_column='id_tipo_usuario', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='application.tipousuario'),
        ),
    ]
