# Generated by Django 5.0.4 on 2024-04-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0053_alter_authuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
