# Generated by Django 5.0.4 on 2024-04-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0054_alter_authuser_id'),
    ]

    operations = [
    ]
