# Generated by Django 5.0.4 on 2024-05-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0059_alter_authuser_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='estado',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
