# Generated by Django 5.0.4 on 2024-05-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0060_alter_tipousuario_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
