# Generated by Django 5.0.4 on 2024-05-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_authuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='last_logout',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
