# Generated by Django 5.0.4 on 2024-05-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0062_authuser_last_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='ultimo_cierre_fecha',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='ultimo_cierre_hora',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='ultimo_ingreso_fecha',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='ultimo_ingreso_hora',
        ),
    ]
