# Generated by Django 5.0.6 on 2024-07-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reporteBeneficiados',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=101)),
                ('grado', models.CharField(max_length=15)),
                ('seccion', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('beneficio', models.CharField(max_length=20)),
                ('id_beneficio', models.IntegerField()),
            ],
            options={
                'db_table': 'reporte_beneficiados',
                'managed': False,
            },
        ),
    ]
