# Generated by Django 5.0.6 on 2024-07-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDeudas',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=101)),
                ('grado', models.CharField(max_length=15)),
                ('seccion', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=20)),
                ('deuda', models.DecimalField(decimal_places=2, max_digits=11)),
                ('id_tipo_pago', models.IntegerField()),
            ],
        ),
    ]
