# Generated by Django 5.0.6 on 2024-07-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_reportedeudas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportedeudas',
            options={'managed': False},
        ),
    ]
