# Generated by Django 5.0.6 on 2024-07-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_reportedeudas_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportedeudas',
            table='reporte_deudas',
        ),
    ]
