# Generated by Django 5.0.6 on 2024-07-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_alter_reportedeudas_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMetodoPago',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=101)),
                ('grado', models.CharField(max_length=15)),
                ('seccion', models.CharField(max_length=15)),
                ('metodo', models.CharField(max_length=30)),
                ('id_metodo', models.BigIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'reporteMetodoPago',
                'managed': False,
            },
        ),
    ]
