# Generated by Django 5.0.6 on 2024-07-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_reportemetodopago'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportemetodopago',
            table='reporte_metodo_pago',
        ),
    ]
