# Generated by Django 4.2.4 on 2024-07-20 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_authuser_ruta_fotografia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0008_reporteingresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermisosReportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('id_tipo_reportes', models.ForeignKey(db_column='id_tipo_reportes', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.tiporeportes')),
                ('id_tipo_usuario', models.ForeignKey(db_column='id_tipo_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='application.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialReportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('id_tipo_reportes', models.ForeignKey(db_column='id_tipo_reportes', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.tiporeportes')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
