# Generated by Django 5.0.4 on 2024-05-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(blank=True, max_length=30, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'configuracion',
            },
        ),
    ]
