# Generated by Django 5.0.4 on 2024-05-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirguracion',
            name='tabla',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
