# Generated by Django 5.0.4 on 2024-05-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_alter_confirguracion_tabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirguracion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
