# Generated by Django 5.0.4 on 2024-05-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_alter_confirguracion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesesMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'meses_mantenimiento',
            },
        ),
    ]
