# Generated by Django 4.2.4 on 2024-05-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_areamantenimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areamantenimiento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mesesmantenimiento',
            options={'managed': False},
        ),
    ]
