# Generated by Django 5.0.4 on 2024-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_confirmacionmantenimiento_gradomantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sexo_mantenimiento',
            },
        ),
    ]
