# Generated by Django 5.0.4 on 2024-05-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_sexomantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(blank=True, max_length=30)),
                ('id_registro', models.IntegerField(blank=True)),
                ('accion', models.CharField(blank=True, max_length=30)),
                ('fecha', models.DateField(blank=True)),
                ('hora', models.TimeField(blank=True)),
                ('usuario_responsable', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'auditoria',
            },
        ),
    ]
