# Generated by Django 4.2.4 on 2024-05-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_metodopagomantenimiento_sexomantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'seccion_mantenimiento',
                'managed': False,
            },
        ),
    ]
