# Generated by Django 5.0.6 on 2024-05-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_auditoria'),
        ('mantenimiento', '0011_turnomantenimiento'),
    ]

    operations = [
    ]
