# Generated by Django 5.0.4 on 2024-09-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0013_alter_auditoria_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaMantenimiento',
        ),
        migrations.DeleteModel(
            name='ConfirmacionMantenimiento',
        ),
        migrations.DeleteModel(
            name='GradoMantenimiento',
        ),
        migrations.DeleteModel(
            name='MesesMantenimiento',
        ),
        migrations.DeleteModel(
            name='MetodoPagoMantenimiento',
        ),
        migrations.DeleteModel(
            name='SeccionMantenimiento',
        ),
        migrations.DeleteModel(
            name='SexoMantenimiento',
        ),
        migrations.DeleteModel(
            name='TipoPagoMantenimiento',
        ),
        migrations.DeleteModel(
            name='TurnoMantenimiento',
        ),
    ]
