# Generated by Django 5.0.4 on 2024-05-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'db_table': 'beneficio',
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(blank=True, max_length=50)),
                ('dni', models.CharField(blank=True, max_length=8)),
                ('nombres', models.CharField(blank=True, max_length=50)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(blank=True, max_length=10)),
                ('departamento_nacimiento', models.CharField(blank=True, max_length=30)),
                ('provincia_nacimiento', models.CharField(blank=True, max_length=30)),
                ('distrito_nacimiento', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('estado_civil', models.DateField(blank=True, max_length=10)),
                ('vive', models.BooleanField(blank=True, default=True)),
                ('vive_con', models.BooleanField(blank=True, default=True)),
                ('apoderado', models.BooleanField(blank=True, default=True)),
                ('celular', models.CharField(blank=True, max_length=9)),
                ('telefono', models.CharField(blank=True, default='S/N', max_length=9)),
                ('departamento_domicilio', models.CharField(blank=True, max_length=30)),
                ('provincia_domicilio', models.CharField(blank=True, max_length=30)),
                ('distrito_domicilio', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('grado_instruccion', models.CharField(blank=True, max_length=30)),
                ('centro_trabajo', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(blank=True, max_length=30)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
