# Generated by Django 5.0.4 on 2024-05-01 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='familiar',
            table='familiar',
        ),
    ]
