# Generated by Django 5.0.4 on 2024-05-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_alumno', '0002_alter_familiar_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
