# Generated by Django 5.0.4 on 2024-05-01 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_alumno', '0003_alter_beneficio_id_alter_familiar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_fotografia', models.CharField(blank=True, default='https://objetivoligar.com/wp-content/uploads/2017/03/blank-profile-picture-973460_1280-580x580.jpg', max_length=255)),
                ('dni', models.CharField(blank=True, max_length=8)),
                ('nombres', models.CharField(blank=True, max_length=50)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(blank=True, max_length=10)),
                ('departamento_nacimiento', models.CharField(blank=True, max_length=30)),
                ('provincia_nacimiento', models.CharField(blank=True, max_length=30)),
                ('distrito_nacimiento', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('lengua_materna', models.CharField(blank=True, max_length=20)),
                ('religion', models.CharField(blank=True, max_length=20)),
                ('parto', models.CharField(blank=True, max_length=20)),
                ('numero_hermanos', models.IntegerField(blank=True)),
                ('departamento_domicilio', models.CharField(blank=True, max_length=30)),
                ('provincia_domicilio', models.CharField(blank=True, max_length=30)),
                ('distrito_domicilio', models.CharField(max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=20)),
                ('situacion', models.CharField(blank=True, max_length=20)),
                ('cod_ie_procedencia', models.CharField(blank=True, max_length=20)),
                ('nivel', models.CharField(blank=True, max_length=15)),
                ('turno', models.CharField(blank=True, max_length=15)),
                ('seccion', models.CharField(blank=True, max_length=15)),
                ('grado', models.CharField(blank=True, max_length=15)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('deuda', models.BooleanField(blank=True, default=True)),
                ('eliminacion_pendiente', models.BooleanField(blank=True, default=False)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id_beneficio', models.ForeignKey(blank=True, db_column='id_beneficio', on_delete=django.db.models.deletion.DO_NOTHING, to='datos_alumno.beneficio')),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
    ]
