# Generated by Django 5.0.4 on 2024-05-01 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_alumno', '0004_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoFamiliar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id_alumno', models.ForeignKey(blank=True, db_column='id_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='datos_alumno.alumno')),
                ('id_familiar', models.ForeignKey(blank=True, db_column='id_familiar', on_delete=django.db.models.deletion.DO_NOTHING, to='datos_alumno.familiar')),
            ],
            options={
                'db_table': 'alumno_x_familiar',
            },
        ),
    ]
