# Generated by Django 5.0.4 on 2024-05-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_alumno', '0005_alumnofamiliar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiantesActivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=8)),
                ('estado', models.BooleanField()),
                ('alumno', models.CharField(max_length=152)),
                ('beneficio', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=15)),
                ('grado', models.CharField(max_length=15)),
                ('seccion', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estudiantes_activos',
            },
        ),
        migrations.CreateModel(
            name='EstudiantesEliminados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=8)),
                ('estado', models.BooleanField()),
                ('alumno', models.CharField(max_length=152)),
                ('beneficio', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=15)),
                ('grado', models.CharField(max_length=15)),
                ('seccion', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estudiantes_eliminados',
            },
        ),
        migrations.CreateModel(
            name='EstudiantesSolicitudEliminacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=8)),
                ('estado', models.BooleanField()),
                ('alumno', models.CharField(max_length=152)),
                ('beneficio', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=15)),
                ('grado', models.CharField(max_length=15)),
                ('seccion', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estudiantes_en_solicitud_eliminacion',
            },
        ),
    ]
