# Generated by Django 4.2.4 on 2024-05-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_alumno', '0007_alter_familiar_estado_civil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantesactivos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estudianteseliminados',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estudiantessolicitudeliminacion',
            options={'managed': False},
        ),
    ]
