# Generated by Django 5.0.4 on 2024-08-28 02:15

import datos_alumno.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_alumno', '0010_alter_alumno_ruta_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='ruta_fotografia',
            field=models.ImageField(default='hombre.png', null=True, upload_to=datos_alumno.models.upload_image),
        ),
    ]
