# Generated by Django 5.0.4 on 2024-09-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_alumno', '0011_alter_alumno_ruta_fotografia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstudiantesActivos',
        ),
        migrations.DeleteModel(
            name='EstudiantesEliminados',
        ),
    ]
