# Generated by Django 5.0.4 on 2024-09-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_alumno', '0012_delete_estudiantesactivos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstudiantesSolicitudEliminacion',
        ),
    ]
