# Generated by Django 5.0.4 on 2024-09-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_alumno', '0013_delete_estudiantessolicitudeliminacion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['dni'], name='alumno_dni_9fb495_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['nombres'], name='alumno_nombres_4c8146_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['apellido_paterno'], name='alumno_apellid_f6e89d_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['apellido_materno'], name='alumno_apellid_86ba76_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['turno'], name='alumno_turno_caa74b_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['grado'], name='alumno_grado_9814ec_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['seccion'], name='alumno_seccion_e81858_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficio',
            index=models.Index(fields=['nombre'], name='beneficio_nombre_76eb25_idx'),
        ),
    ]
