# Generated by Django 5.0.6 on 2024-05-24 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_turnocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.DO_NOTHING, to='caja.caja')),
                ('id_turno_caja', models.ForeignKey(db_column='id_turno_caja', on_delete=django.db.models.deletion.DO_NOTHING, to='caja.turnocaja')),
            ],
            options={
                'db_table': 'apertura',
            },
        ),
    ]
