# Generated by Django 5.0.6 on 2024-07-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'apertura_caja',
            },
        ),
        migrations.CreateModel(
            name='AperturaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('id_apertura', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'apertura_movimiento',
            },
        ),
        migrations.CreateModel(
            name='HistorialPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('alumno', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_de_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'historial_pagos',
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apertura',
            name='fecha_cierre',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
