# Generated by Django 5.0.6 on 2024-07-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMetodosPagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=15)),
                ('seccion', models.CharField(max_length=15)),
                ('metodo', models.CharField(blank=True, max_length=30, null=True)),
                ('id_metodo', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'reporte_metodo_pago',
                'managed': False,
            },
        ),
    ]
